### ISSUE TITLE
What's the reason to use AbstractSoftEntity and AbstractEntity?

### ISSUE THREAD

**Issue by eagle8625** [gtiwari333/spring-boot-data-jpa-mongodb-rest-angularjs#1]
Hi, I have a question about AbstractSoftEntity and AbstractEntity. I found AbstractSoftEntity extend AbstractEntity. What's the purpose for this? Thanks in advance.

**Comment by gtiwari333** [comment]
Hello, 

I was intending to create a repository that does a soft delete ( opposite of physical record deletion). For this purpose, I created AbstractSoftEntity with a field "deleted" that indicates if the record is active or not.

For now, you can just ignore it. The soft delete logic is not implemented yet.

```
@Field( "deleted" )
	@JsonIgnore
	private boolean				deleted				= false;
```
